{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1623156737021, "stop": 1623156737021, "uuid": "92c6b3c9-6973-412e-8578-b74bdf2551b9", "historyId": "44c5e46764f73a56326e54cefd8e8e86", "testCaseId": "7f751c4c09f6823767f5ddca0787ab1c", "fullName": "Test_BlogAllure#test_xfail_unexpected_pass", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=<function <lambda> at 0x000001DF13A831F0>, reason='this test is expecting failure')"}, {"name": "suite", "value": "Test_BlogAllure"}, {"name": "host", "value": "MININT-I84MTFS"}, {"name": "thread", "value": "25880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_BlogAllure"}]}