{"name": "test_xfail_expected_failure", "status": "skipped", "statusDetails": {"message": "XFAIL this test is expecting failure\n\nAssertionError: assert False", "trace": "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n        print(\"this test is an xfail that will be marked as expected failure\")\n>       assert False\nE       assert False\n\nTest_BlogAllure.py:25: AssertionError"}, "description": "this test is an xfail that will be marked as expected failure", "attachments": [{"name": "stdout", "source": "2c468f25-46a1-4436-8159-d6375fcaa257-attachment.txt", "type": "text/plain"}], "start": 1623156792173, "stop": 1623156792173, "uuid": "33c6f06c-00ee-4ae2-91b5-794c73f56927", "historyId": "1daaa093acc71b060a3d904614b9a40d", "testCaseId": "d4ed2c55360bcf4ee65a722ae6965c7a", "fullName": "Test_BlogAllure#test_xfail_expected_failure", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=<function <lambda> at 0x000001B0BABDE1F0>, reason='this test is expecting failure')"}, {"name": "suite", "value": "Test_BlogAllure"}, {"name": "host", "value": "MININT-I84MTFS"}, {"name": "thread", "value": "14344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_BlogAllure"}]}