{"name": "test_xfail_expected_failure", "status": "skipped", "statusDetails": {"message": "XFAIL this test is expecting failure\n\nAssertionError: assert False", "trace": "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\nTest_BlogAllure.py:24: AssertionError"}, "description": "this test is an xfail that will be marked as expected failure", "start": 1623156737016, "stop": 1623156737016, "uuid": "449295ee-7e5b-4826-850e-b7fe9afb16c4", "historyId": "1daaa093acc71b060a3d904614b9a40d", "testCaseId": "d4ed2c55360bcf4ee65a722ae6965c7a", "fullName": "Test_BlogAllure#test_xfail_expected_failure", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=<function <lambda> at 0x000001DF13A83040>, reason='this test is expecting failure')"}, {"name": "suite", "value": "Test_BlogAllure"}, {"name": "host", "value": "MININT-I84MTFS"}, {"name": "thread", "value": "25880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_BlogAllure"}]}